version: "3.9"
services:
  backend:
    image: "ethics-backend"
    depends_on:
      clamav:
        condition: service_healthy
      database:
        condition: service_healthy
    environment:
      ETHICS_FRONTEND_URL: "http://localhost"
      DATABASE_URL: "jdbc:postgresql://database:5432/ethics"
    ports:
      - 8081:8080
  frontend:
    image: "ethics-frontend"
    environment:
      PORT: 80
    ports:
      - 80:80
  clamav:
    image: "clamav/clamav"
    ports:
     - 3310:3310
  database:
    image: "postgres"
    restart: "always"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "ethicsuser"
      POSTGRES_PASSWORD: "ADD_DB_PASS_HERE"
      POSTGRES_DB: "ethics"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
volumes:
  postgres-db-data:
